# https://docs.docker.jp/compose/compose-file/compose-versioning.html
version: "3.8"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:latest
    container_name: mysql-sample-container
    environment:
      TZ: 'Asis/Tokyo'
    ports:
      # 3306:3306だと接続に失敗する(理由は、3306を別のプロセスが使ってる)
      - "3306:3306"
    env_file:
      - mysql/.env