# https://docs.docker.jp/compose/compose-file/compose-versioning.html
version: "3.8"

services:
  db-mysql:
    container_name: db-mysql-container
    build: ./mysql
    env_file:
      - mysql/.env
    ports:
      # 3306:3306だと接続に失敗する(理由は、3306を別のプロセスが使ってる)
      - "3306:3306"
