# M1 Macは、platform指定がないとエラー
FROM --platform=linux/x86_64 mysql:latest

# https://hub.docker.com/_/mysql
ENV MYSQL_DATABASE=db-mysql
ENV MYSQL_USER=mysql_user
ENV MYSQL_PASSWORD=PHOY8josh6bleb4megh
ENV MYSQL_ROOT_PASSWORD=PHOY8josh6bleb4megh